#!/bin/bash
source ~/.bashrc
export PATH="$PATH:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/netsvcs/bin"
# Backup script for Experience Manager databases.

# Set backup file name:
BACKPATH=/home/netsvcs/sqlback
BACKFILE=`date +"%Y-%m-%d-%H.sql"`

# Remove any backups older than 30 days:
if [ "$(find ${BACKPATH}/ -type f | wc -l)" -gt "5"  ] && [ -n "$(find ${BACKPATH}/ -type f -mtime +30)" ]; then
 find ${BACKPATH}/ -type f -mtime +30 -print0 | xargs -0 rm
fi

# Check for presence of VIP
if [ -z "$(ifconfig | grep $(grep dbvip /etc/hosts | cut -d " " -f 1))" ]; then
 echo "DBVIP not on this machine, skipping."
 exit 0
fi

# Create database dumps for listed databases, with login credentials.
/usr/bin/mysqldump -u netsvcs -p'not4dev!' -h dbvip \
        --opt --skip-lock-tables --single-transaction --flush-logs --routines \
        --databases exm \
        | gzip -c > ${BACKPATH}/db-${BACKFILE}-$(hostname -s).gz

# Replicate the backups and any deletions to app02:
#rsync -a --delete ${BACKPATH}/ netsvcs@master:${BACKPATH}

#Replicate new files to other server:
/usr/bin/rsync -a ${BACKPATH}/ netsvcs@master:${BACKPATH}
