rm -f /home/config_files/app01/*
rm -f /home/config_files/app02/*
rm -f /home/config_files/media01/*
rm -f /home/config_files/media02/*
rm -f /home/config_files/lb01/*
rm -f /home/config_files/lb02/*


cp /etc/httpd/conf.d/v2-admin.conf /etc/httpd/conf.d/v2-client.conf /etc/httpd/conf/httpd.conf /etc/tomcat7/v2-log4j.xml /etc/tomcat7/server.xml /etc/tomcat7/tomcat7.conf /etc/tomcat7/Catalina/prod.uiexm.com/v2.xml /etc/tomcat7/Catalina/prod.uiexm.com/location.xml /etc/tomcat7/Catalina/prod.uiexm.com/leaderboard.xml /etc/tomcat7/Catalina/prod.uiexm.com/loyalty.json /etc/tomcat7/Catalina/prod.uiexm.com/excursions.xml /etc/tomcat7/Catalina/prod.uiexm.com/facegame.xml /etc/tomcat7/sites-available/prod.uiexm.com.xml /usr/local/nacos/properties.uie /etc/ha.d/ha.cf /etc/ha.d/haresources /etc/my.cnf /etc/monit.d/mutedaemon /etc/monit.d/unison /etc/monit.d/nacos /etc/monit.d/nodejs /etc/monit.d/storage-ha /etc/monit.d/node-mute /etc/tomcat7/Catalina/prod.uiexm.com/location.xml /root/weatherupdate/currentupdate.sh /root/weatherupdate/forecastupdate.sh /usr/local/bin/deploy.sh /usr/local/bin/properties.uie /usr/local/bin/mnc /usr/local/bin/cleancache.sh /usr/local/bin/hal-shutdown.sh /usr/local/bin/storage-ha.sh /usr/local/bin/ship /home/netsvcs/bin/backupdb /root/.unison/default.prf /home/config_files/app01

scp app02:/etc/httpd/conf.d/v2-admin.conf app02:/etc/httpd/conf.d/v2-client.conf app02:/etc/httpd/conf/httpd.conf app02:/etc/tomcat7/v2-log4j.xml app02:/etc/tomcat7/server.xml app02:/etc/tomcat7/tomcat7.conf app02:/etc/tomcat7/Catalina/prod.uiexm.com/v2.xml app02:/etc/tomcat7/Catalina/prod.uiexm.com/location.xml app02:/etc/tomcat7/Catalina/prod.uiexm.com/leaderboard.xml app02:/etc/tomcat7/Catalina/prod.uiexm.com/loyalty.json app02:/etc/tomcat7/Catalina/prod.uiexm.com/excursions.xml app02:/etc/tomcat7/Catalina/prod.uiexm.com/facegame.xml app02:/etc/tomcat7/sites-available/prod.uiexm.com.xml app02:/usr/local/nacos/properties.uie app02:/etc/ha.d/ha.cf app02:/etc/ha.d/haresources app02:/etc/my.cnf app02:/etc/monit.d/mutedaemon app02:/etc/monit.d/unison app02:/etc/monit.d/nacos app02:/etc/monit.d/nodejs app02:/etc/monit.d/storage-ha app02:/etc/monit.d/node-mute app02:/etc/tomcat7/Catalina/prod.uiexm.com/location.xml app02:/root/weatherupdate/currentupdate.sh app02:/root/weatherupdate/forecastupdate.sh app02:/usr/local/bin/deploy.sh app02:/usr/local/bin/properties.uie app02:/usr/local/bin/mnc app02:/usr/local/bin/cleancache.sh app02:/usr/local/bin/hal-shutdown.sh app02:/usr/local/bin/storage-ha.sh app02:/usr/local/bin/ship app02:/home/netsvcs/bin/backupdb app02:/root/.unison/default.prf /home/config_files/app02

scp media01:/etc/httpd/conf/httpd.conf media01:/etc/httpd/conf.d/vhosts.conf media01:/etc/tomcat7/log4j.xml media01:/etc/tomcat7/server.xml media01:/etc/tomcat7/tomcat7.conf media01:/etc/tomcat7/Catalina/prod.uiexm.com/v2.xml media01:/etc/tomcat7/sites-available/prod.uiexm.com.xml media01:/etc/ha.d/haresources media01:/etc/ha.d/ha.cf media01:/etc/nginx/sites-available/media.conf media01:/etc/nginx/sites-available/procentric.conf media01:/etc/nginx/sites-available/ssl.conf media01:/etc/nginx/sites-enabled/procentric.conf media01:/etc/nginx/sites-enabled/media.conf media01:/etc/init.d/Wowzaunmute media01:/etc/init.d/WowzaStreamingEngine media01:/usr/local/WowzaStreamingEngine/bin/WowzaStreamingEngine media01:/usr/local/bin/storage-ha.sh media01:/usr/local/bin/deploy.sh media01:/usr/local/bin/cleancache.sh media01:/usr/local/bin/hal-shutdown.sh media01:/usr/local/bin/storage-ha.sh media01:/usr/local/bin/wowperf.sh media01:/usr/local/bin/mutedaem/properties.uie media01:/usr/local/WowzaStreamingEngine/conf/mobiletv/Application.xml media01:/usr/local/WowzaStreamingEngine/conf/Server.xml media01:/root/.unison/default.prf media01:/nfs/m1/procentric/procentric/system/LGService.xml media01:/nfs/m1/procentric/procentric/application/xait.xml media01:/etc/monit.d/WowzaUnmute media01:/etc/monit.d/unison media01:/etc/monit.d/WowzaStreamingEngine media01:/etc/monit.d/storage-ha /home/config_files/media01

scp media02:/etc/httpd/conf/httpd.conf media02:/etc/httpd/conf.d/vhosts.conf media02:/etc/tomcat7/log4j.xml media02:/etc/tomcat7/server.xml media02:/etc/tomcat7/tomcat7.conf media02:/etc/tomcat7/Catalina/prod.uiexm.com/v2.xml media02:/etc/tomcat7/sites-available/prod.uiexm.com.xml media02:/etc/ha.d/haresources media02:/etc/ha.d/ha.cf media02:/etc/nginx/sites-available/media.conf media02:/etc/nginx/sites-available/procentric.conf media02:/etc/nginx/sites-available/ssl.conf media02:/etc/nginx/sites-enabled/procentric.conf media02:/etc/nginx/sites-enabled/media.conf media02:/etc/init.d/Wowzaunmute media02:/etc/init.d/WowzaStreamingEngine media02:/usr/local/WowzaStreamingEngine/bin/WowzaStreamingEngine media02:/usr/local/bin/storage-ha.sh media02:/usr/local/bin/deploy.sh media02:/usr/local/bin/cleancache.sh media02:/usr/local/bin/hal-shutdown.sh media02:/usr/local/bin/storage-ha.sh media02:/usr/local/bin/wowperf.sh media02:/usr/local/bin/mutedaem/properties.uie media02:/usr/local/WowzaStreamingEngine/conf/mobiletv/Application.xml media02:/usr/local/WowzaStreamingEngine/conf/Server.xml media02:/root/.unison/default.prf media02:/nfs/m1/procentric/procentric/system/LGService.xml media02:/nfs/m1/procentric/procentric/application/xait.xml media02:/etc/monit.d/WowzaUnmute media02:/etc/monit.d/unison media02:/etc/monit.d/WowzaStreamingEngine media02:/etc/monit.d/storage-ha /home/config_files/media02

scp lb01:/etc/haproxy/haproxy.cfg lb01:/etc/ha.d/haresources lb01:/etc/ha.d/ha.cf lb01:/etc/hosts /home/config_files/lb01

scp lb02:/etc/haproxy/haproxy.cfg lb02:/etc/ha.d/haresources lb02:/etc/ha.d/ha.cf lb02:/etc/hosts /home/config_files/lb02
